# Generated by Django 2.1.2 on 2018-11-06 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import restrito.models.usuario


class Migration(migrations.Migration):

    dependencies = [
        ('restrito', '0003_professor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome Completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('apelido', models.CharField(max_length=120, verbose_name='Apelido')),
            ],
            options={
                'db_table': 'ALUNO',
            },
        ),
        migrations.CreateModel(
            name='AlunoUsuario',
            fields=[
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'proxy': True,
                'indexes': [],
            },
            bases=('restrito.usuario',),
            managers=[
                ('objects', restrito.models.usuario.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfessorUsuario',
            fields=[
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'proxy': True,
                'indexes': [],
            },
            bases=('restrito.usuario',),
            managers=[
                ('objects', restrito.models.usuario.UsuarioManager()),
            ],
        ),
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.CharField(max_length=120, unique=True, verbose_name='Nome de Usuário'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
