# Generated by Django 2.1.2 on 2018-10-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0002_auto_20181023_2044'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='curso',
            table='CURSOS',
        ),
    ]
