# Generated by Django 2.1.2 on 2018-10-29 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0003_auto_20181029_1333'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='curso',
            table='CURSO',
        ),
    ]
