# Generated by Django 2.1.2 on 2018-10-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0007_auto_20181030_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinasofertadas',
            name='semestre',
            field=models.CharField(default='n', max_length=120, verbose_name='Semestre'),
        ),
    ]
