# Generated by Django 2.0.6 on 2018-10-30 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0009_auto_20181030_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplinasofertadas',
            options={'verbose_name': 'Disciplina Ofertada'},
        ),
        migrations.AddField(
            model_name='disciplinasofertadas',
            name='disciplina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='curriculo.Disciplina'),
        ),
    ]
