# Generated by Django 2.0.6 on 2018-10-30 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0010_auto_20181030_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplinasofertadas',
            options={'verbose_name': 'Disciplina Ofertada', 'verbose_name_plural': 'Disciplinas Ofertadas'},
        ),
    ]
