# Generated by Django 2.0.6 on 2018-10-31 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0011_auto_20181030_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinasofertadas',
            name='nome',
        ),
        migrations.AddField(
            model_name='disciplinasofertadas',
            name='ano',
            field=models.IntegerField(null=True, verbose_name='Ano'),
        ),
    ]
