# Generated by Django 2.1.2 on 2018-10-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0012_auto_20181030_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='abrev',
            field=models.CharField(max_length=5, null=True, verbose_name='Abreviação'),
        ),
    ]
