# Generated by Django 2.1.2 on 2018-10-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0014_auto_20181031_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='descricao',
            field=models.TextField(max_length=500, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='ementa',
            field=models.TextField(max_length=500, null=True, verbose_name='Ementa'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='abrev',
            field=models.CharField(default='Abreviação', max_length=10, unique=True, verbose_name='Abreviação'),
        ),
    ]
